version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229 # fallback port
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    networks:
      - webnet
    environment:
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      # Opens port 3306 on the container
      - '3306'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  webnet:
volumes:
  mysql-data:
